language: php
php:
#  - '7.1' incompatible since add Symfony/Panther. It's require PHP 7.2 min.
  - '7.2'
  - '7.3'
  - nightly

#  Use when we do functional test with Panther
#addons:
#  chrome: stable

cache:
  directories:
  - $HOME/.composer/cache

before_script:
  - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.12.1/php-cs-fixer.phar
  - wget https://github.com/phpstan/phpstan/releases/download/0.10.2/phpstan.phar
  - composer install


script:
  - phpunit
  - php php-cs-fixer.phar fix --dry-run --diff --no-ansi
  - php phpstan.phar analyse src tests --level=6