language: php
php:
#  - '7.1' incompatible since add Symfony/Panther. It's require PHP 7.2 min.
  - '7.2'
#  - nightly #Last hot version

#  Use when we do functional test with Panther
addons:
  chrome: stable

cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.12.1/php-cs-fixer.phar

before_script:
  - phpenv config-rm xdebug.ini
  - composer install


script:
  - php bin/phpunit
  - php php-cs-fixer.phar fix --dry-run --diff --no-ansi src
  - vendor/bin/phpstan analyse src tests --level=6