index:
    path: /
    controller: App\Controller\DefaultController::index
    
admin_test:
    path: /_secure/test
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: admin/test.html.twig

profile_logout:
    path: /profile/logout

admin_logout:
    path: /_secure/logout
